const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');

test('Add Player creates an editable free agent that survives export',async()=>{
 const server=http.createServer((req,res)=>{
  const filename=path.join(root,new URL(req.url,'http://localhost').pathname);
  if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return}
  try{res.setHeader('Content-Type',filename.endsWith('.js')?'text/javascript':filename.endsWith('.css')?'text/css':filename.endsWith('.png')?'image/png':filename.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(filename))}catch{res.writeHead(404).end()}
 });
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 let browser;
 try{
  browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/index.html`);
  const template=JSON.parse(fs.readFileSync(path.join(root,'templates/pro/ProTemplate1.txt'),'utf8'));
  await page.locator('#import').setInputFiles({name:'add-player-test.txt',mimeType:'text/plain',buffer:Buffer.from(JSON.stringify(template))});
  await page.waitForTimeout(300);assert.deepEqual(errors,[]);
  await page.waitForFunction(()=>document.querySelector('#teams button'));
  await page.locator('#leagueNav').evaluate(button=>button.click());
  const order=await page.locator('.configuration-card').evaluate(card=>{
   const summaries=[...card.querySelectorAll(':scope > details > summary')];
   return summaries.map(summary=>summary.textContent.trim()).filter(name=>/Simulation Sliders|Free Agents|Retired Numbers/.test(name));
  });
  assert.match(order[0],/Simulation Sliders/);
  assert.match(order[1],/Free Agents/);
  assert.match(order[2],/Retired Numbers/);
  await page.setViewportSize({width:1200,height:850});
  await page.locator('.free-agents-editor > summary').click();
  assert.equal(await page.locator('.free-agents-editor .roster-manager').count(),1);
  assert.equal(await page.getByRole('button',{name:'Manage Free Agents'}).count(),0);
  await page.locator('.free-agents-editor .roster-list-panel').getByRole('button',{name:'Add Player'}).click();
  await page.locator('.free-agents-editor .roster-player-panel').getByRole('heading',{name:'New Free Agent'}).waitFor();
  assert.equal(await page.getByLabel('Potential',{exact:true}).first().getAttribute('max'),'10');
  const potentialStepper=page.getByLabel('Potential',{exact:true}).first().locator('..');
  assert.equal(await potentialStepper.locator('button').count(),2);
  const appearanceSettings=page.locator('.free-agents-editor .roster-appearance-settings');
  assert.equal(await appearanceSettings.locator('summary').textContent(),'Skin, eyes & hair');
  assert.equal(await appearanceSettings.evaluate(details=>details.open),false);
  await appearanceSettings.locator('summary').click();
  assert(await page.getByLabel('Skin',{exact:true}).isVisible());
  const skinBox=await page.getByLabel('Skin',{exact:true}).boundingBox(),hairStyleBox=await page.getByLabel('Hair style').boundingBox();
  assert(skinBox&&skinBox.width<=64,`Skin color picker should be compact: ${JSON.stringify(skinBox)}`);
  assert(hairStyleBox&&hairStyleBox.width<=280,`Hair style selector should be compact: ${JSON.stringify(hairStyleBox)}`);
  const attributesSection=page.locator('.free-agents-editor .roster-attributes-section'),skillsSection=page.locator('.free-agents-editor .roster-skills-section');
  assert.equal(await attributesSection.evaluate(details=>details.open),false);
  assert.equal(await skillsSection.evaluate(details=>details.open),false);
  const uniforms=page.locator('.roster-uniform-tabs');
  assert.deepEqual(await uniforms.locator('button').allTextContents(),['Home','Road','Alt 1','Alt 2']);
  await uniforms.getByRole('button',{name:'Alt 2'}).click();
  assert.equal(await page.locator('.roster-accessories > summary').textContent(),'Alt 2 accessories');
  await uniforms.getByRole('button',{name:'Road'}).click();
  assert.equal(await uniforms.getByRole('button',{name:'Road'}).getAttribute('aria-pressed'),'true');
  assert.equal(await uniforms.getByRole('button',{name:'Home'}).getAttribute('aria-pressed'),'false');
  assert.equal(await page.locator('.roster-accessories > summary').textContent(),'Road accessories');
  assert.deepEqual(await page.locator('.free-agents-editor .roster-accessory-group > summary').allTextContents(),['Head','Arms','Legs','Shoes']);
  await page.locator('#toast').evaluate(toast=>toast.style.display='none');
  await page.locator('.free-agents-editor').screenshot({path:path.join(root,'artifacts/free-agents-inline.png')});
  await page.getByLabel('First name',{exact:true}).fill('Jordan');
  await page.getByLabel('Last name',{exact:true}).fill('Example');
  await page.getByLabel('Position',{exact:true}).selectOption('2');
  await page.getByLabel('Hair style').selectOption('0002');
  await page.getByLabel('Skin').fill('#a36342');
  await page.getByLabel('Skin').dispatchEvent('input');
  await page.locator('.roster-accessories > summary').click();
  await page.locator('.free-agents-editor .roster-accessory-group').filter({has:page.getByText('Head',{exact:true})}).locator('summary').click();
  await page.getByLabel('Head accessory color team color',{exact:true}).selectOption('SEC');
  await page.locator('.free-agents-editor .roster-accessory-group').filter({has:page.getByText('Shoes',{exact:true})}).locator('summary').click();
  await page.getByLabel('Socks custom color').fill('#22cc88');
  await page.getByLabel('Socks custom color').dispatchEvent('input');
  await attributesSection.locator('summary').click();
  await page.locator('.free-agents-editor .roster-attributes input[aria-label="Current"]').first().fill('9');
  await page.locator('.free-agents-editor .roster-attributes input[aria-label="Current"]').first().dispatchEvent('change');
  await skillsSection.locator('summary').click();
  await page.locator('.free-agents-editor').getByRole('button',{name:'Add skill'}).click();
  await page.locator('.free-agents-editor .roster-skill').first().getByLabel('Skill').selectOption('BUL');
  await page.getByRole('button',{name:'Create Free Agent'}).click();
  await page.locator('.free-agents-editor .roster-list').getByText(/Jordan Example/).waitFor();
  assert.equal(await page.locator('#title').textContent(),template.leagueName);
  assert.equal(await page.locator('.free-agents-editor').evaluate(section=>section.open),true);
  await page.getByLabel('Nickname',{exact:true}).fill('J');
  await page.getByLabel('Nickname',{exact:true}).dispatchEvent('change');
  const canvas=page.locator('.roster-appearance canvas').first();
  await canvas.waitFor();
  assert.deepEqual(await canvas.evaluate(c=>({width:c.width,height:c.height})),{width:64,height:84});
  await page.waitForFunction(()=>{const c=document.querySelector('.roster-appearance canvas');return c&&[...c.getContext('2d').getImageData(0,0,c.width,c.height).data].some((v,i)=>i%4===3&&v>0)});
  const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').evaluate(button=>button.click())]);
  const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  const added=exported.freeAgents.find(player=>player.fn==='Jordan'&&player.ln==='Example');
  assert(added);
  assert(added.id>0);
  assert(!template.teams.some(team=>team.roster.some(player=>player.id===added.id)));
  assert.equal(added.tid,0);
  assert.equal(added.pos,2);
  assert.equal(added.appearance.hair,'0002');
  assert.equal(added.appearance.skinC,'A36342');
  assert.equal(added.accessories[1].headAccC,'SEC');
  assert.equal(added.accessories[1].sockC,'22CC88');
  assert.notEqual(added.accessories[0].sockC,'22CC88');
  assert.equal(added.tag,'J');
  assert.equal(added.attributes.LAY[0],9);
  assert.equal(added.skills[0].id,'BUL');
  assert(added.attributes&&added.contract&&added.accessories);
  if(!await page.locator('.free-agents-editor').evaluate(section=>section.open))await page.locator('.free-agents-editor > summary').click();
  const destination=Number(await page.getByLabel('Destination team').inputValue());
  assert((await page.locator('.free-agents-editor .roster-player-panel button').allTextContents()).some(text=>text.includes('Add to team')),
   `Editor buttons: ${await page.locator('.free-agents-editor .roster-player-panel button').allTextContents()}`);
  await page.getByRole('button',{name:'Add to team'}).click();
  assert.equal(await page.locator('#title').textContent(),template.leagueName);
  assert.equal(await page.locator('.free-agents-editor .roster-list .roster-player').count(),0);
  const [movedDownload]=await Promise.all([page.waitForEvent('download'),page.locator('#export').evaluate(button=>button.click())]);
  const movedLeague=JSON.parse(fs.readFileSync(await movedDownload.path(),'utf8'));
  assert.equal(movedLeague.freeAgents.some(player=>player.id===added.id),false);
  assert.equal(movedLeague.teams[destination].roster.some(player=>player.id===added.id),true);
  assert.deepEqual(errors,[]);
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
});
